#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

if hash wget; then
  wget 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz' -cO data/t10k-images.idx3-ubyte.gz
  wget 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz' -cO data/t10k-labels.idx1-ubyte.gz
  wget 'https://github.com/simnalamburt/i/raw/master/snucse.hsd/mlp_iter_10000.caffemodel' -cO pretrained_weights/mlp_iter_10000.caffemodel
elif hash curl; then
  curl 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz' -LC- -o data/t10k-images.idx3-ubyte.gz
  curl 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz' -LC- -o data/t10k-labels.idx1-ubyte.gz
  curl 'https://github.com/simnalamburt/i/raw/master/snucse.hsd/mlp_iter_10000.caffemodel' -LC- -o pretrained_weights/mlp_iter_10000.caffemodel
else
  echo 'curl or wget is required'
  exit 1
fi

b2sum -c <<< "\
b1115f28ddd2e52c792383c291b98947d6071a5723c45b53d9b974ab9a38d0d8de22f46c93d7c9a88f7d5b2195a45a3e58f100ac1522c734142208cf2129ed91  data/t10k-images.idx3-ubyte.gz
64ea2b274ad89f0f19fca90c5aea1bf99b9dbe9ebe95f8c5cfec1fdbcdaba9854b69575fbb7da40c430ce200cdcb6f7cf203826011d25217a8178e0f38d3c5a1  data/t10k-labels.idx1-ubyte.gz
db157b40d5c6f7748e83e053c63e456b1be352c77022dd55db023fa12eca29e87dfcdbe64c6847e33a63b5544c8afef6b316e0f8b11d3710c386cef110c1c4ed  pretrained_weights/mlp_iter_10000.caffemodel"

gzip -dkf data/{t10k-images.idx3-ubyte,t10k-labels.idx1-ubyte}.gz
