#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

if hash wget; then
  wget 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz' -cO data/t10k-images.idx3-ubyte.gz
  wget 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz' -cO data/t10k-labels.idx1-ubyte.gz
  wget 'https://github.com/simnalamburt/i/raw/master/snucse.hsd/mlp_iter_10000.caffemodel' -cO pretrained_weights/mlp_iter_10000.caffemodel
  wget 'https://github.com/simnalamburt/i/raw/master/snucse.hsd/cnn_weights.txt.xz' -cO pretrained_weights/cnn_weights.txt.xz
elif hash curl; then
  curl 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz' -LC- -o data/t10k-images.idx3-ubyte.gz
  curl 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz' -LC- -o data/t10k-labels.idx1-ubyte.gz
  curl 'https://github.com/simnalamburt/i/raw/master/snucse.hsd/mlp_iter_10000.caffemodel' -LC- -o pretrained_weights/mlp_iter_10000.caffemodel
  curl 'https://github.com/simnalamburt/i/raw/master/snucse.hsd/cnn_weights.txt.xz' -LC- -o pretrained_weights/cnn_weights.txt.xz
else
  echo 'curl or wget is required'
  exit 1
fi

sha256sum -c <<< "\
8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6  data/t10k-images.idx3-ubyte.gz
f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6  data/t10k-labels.idx1-ubyte.gz
cdf0cc09f82d3e35d5d4d1126bad7f46a9107b06f955b646ca9f4954d8dc9a7a  pretrained_weights/mlp_iter_10000.caffemodel
d0e5a9849d45da1ac407aeda3884573d606e70e66e70010fe892e8cdfbe80359  pretrained_weights/cnn_weights.txt.xz"

gzip -dkf data/{t10k-images.idx3-ubyte,t10k-labels.idx1-ubyte}.gz
xz -dkf pretrained_weights/cnn_weights.txt.xz
